/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package queenslain;

//import javax.swing.JOptionPane;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class Table extends javax.swing.JFrame {
    // vetor para armazenar as posições das rainhas. 
    public String coluna1, coluna2, coluna3, coluna4, linha1, linha2, linha3, linha4;
    String[][] vetor = new String [4][4];
   // protected int numQueens = 0;
    Numero num = new Numero();

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
    }
    /*
    private boolean checkNumQueens() {
        if (this.numQueens < 4) {
             this.numQueens += 1;
             return true;
        }else {
            JOptionPane.showMessageDialog(null, "Você pode usar apenas 4 Rainhas!");
            return false;
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();
        c10 = new javax.swing.JButton();
        c11 = new javax.swing.JButton();
        c12 = new javax.swing.JButton();
        c13 = new javax.swing.JButton();
        c14 = new javax.swing.JButton();
        c15 = new javax.swing.JButton();
        c16 = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        checarResposta = new javax.swing.JButton();
        reiniciar1 = new javax.swing.JButton();
        status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRegras = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Jogo"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        c1.setBackground(new java.awt.Color(0, 0, 0));
        c1.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.setBackground(new java.awt.Color(204, 102, 0));
        c2.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.setBackground(new java.awt.Color(0, 0, 0));
        c3.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c4.setBackground(new java.awt.Color(204, 102, 0));
        c4.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        c5.setBackground(new java.awt.Color(204, 102, 0));
        c5.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c5.setForeground(new java.awt.Color(255, 255, 255));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        c6.setBackground(new java.awt.Color(0, 0, 0));
        c6.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        c7.setBackground(new java.awt.Color(204, 102, 0));
        c7.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c7.setForeground(new java.awt.Color(255, 255, 255));
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });

        c8.setBackground(new java.awt.Color(0, 0, 0));
        c8.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c8.setForeground(new java.awt.Color(255, 255, 255));
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });

        c9.setBackground(new java.awt.Color(0, 0, 0));
        c9.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c9.setForeground(new java.awt.Color(255, 255, 255));
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });

        c10.setBackground(new java.awt.Color(204, 102, 0));
        c10.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c10.setForeground(new java.awt.Color(255, 255, 255));
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });

        c11.setBackground(new java.awt.Color(0, 0, 0));
        c11.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c11.setForeground(new java.awt.Color(255, 255, 255));
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });

        c12.setBackground(new java.awt.Color(204, 102, 0));
        c12.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c12.setForeground(new java.awt.Color(255, 255, 255));
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });

        c13.setBackground(new java.awt.Color(204, 102, 0));
        c13.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c13.setForeground(new java.awt.Color(255, 255, 255));
        c13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c13ActionPerformed(evt);
            }
        });

        c14.setBackground(new java.awt.Color(0, 0, 0));
        c14.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c14.setForeground(new java.awt.Color(255, 255, 255));
        c14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c14ActionPerformed(evt);
            }
        });

        c15.setBackground(new java.awt.Color(204, 102, 0));
        c15.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c15.setForeground(new java.awt.Color(255, 255, 255));
        c15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c15ActionPerformed(evt);
            }
        });

        c16.setBackground(new java.awt.Color(0, 0, 0));
        c16.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        c16.setForeground(new java.awt.Color(255, 255, 255));
        c16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c16ActionPerformed(evt);
            }
        });

        reiniciar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });

        checarResposta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        checarResposta.setText("Checar Resposta");
        checarResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarRespostaActionPerformed(evt);
            }
        });

        reiniciar1.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        reiniciar1.setText("Desistir");
        reiniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciar1ActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        txtRegras.setEditable(false);
        txtRegras.setBackground(new java.awt.Color(238, 238, 238));
        txtRegras.setColumns(20);
        txtRegras.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtRegras.setLineWrap(true);
        txtRegras.setRows(5);
        txtRegras.setText("- As rainhas de um tabuleiro de xadrez \npodem atacar na vertical, horizontal \ne diagonal.\n\n- Como posicionar 4 rainhas no \ntabuleiro 4x4 sem que um par de \nrainhas possam se atacar?\n\n- Como deve ser a estrutura da \nsolução para o problema?");
        txtRegras.setAutoscrolls(false);
        txtRegras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 238), 1, true));
        jScrollPane1.setViewportView(txtRegras);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 48)); // NOI18N
        jLabel1.setText("Queen Slain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checarResposta, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(status)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reiniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(303, 303, 303))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c16, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addGap(18, 18, 18)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(reiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addComponent(checarResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reiniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c16ActionPerformed
        // casa 16
        if (num.checkNumQueens()){
            c16.setText("Q");
            vetor[3][3] = "Q";
        } 
    }//GEN-LAST:event_c16ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        //casa 1
        if (num.checkNumQueens()){
            c1.setText("Q");
            vetor[0][0] = "Q";
        } 
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        //casa 2 
        if (num.checkNumQueens()){
            c2.setText("Q");
            vetor[1][0] = "Q";
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // casa 3 
        if (num.checkNumQueens()){
            c3.setText("Q");
            vetor[2][0] = "Q";
        }
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // casa 4
        if (num.checkNumQueens()){
            c4.setText("Q");
            vetor[3][0] = "Q";
        }
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // casa 5 
        if (num.checkNumQueens()){
            c5.setText("Q");
            vetor[0][1] = "Q";
        }    
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // casa 6
        if (num.checkNumQueens()){
            c6.setText("Q");
            vetor[1][1] = "Q";
        }
    }//GEN-LAST:event_c6ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // casa 7 
        if (num.checkNumQueens()){
            c7.setText("Q");
            vetor[2][1] = "Q";
        }    
    }//GEN-LAST:event_c7ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // casa 8
        if (num.checkNumQueens()){
            c8.setText("Q");
            vetor[3][1] = "Q";
        }
    }//GEN-LAST:event_c8ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // casa 9 
        if (num.checkNumQueens()){
            c9.setText("Q");
            vetor[0][2] = "Q";
        }
    }//GEN-LAST:event_c9ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // casa 10
        if (num.checkNumQueens()){
            c10.setText("Q");
            vetor[1][2] = "Q";
        }
    }//GEN-LAST:event_c10ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // casa 11
        if (num.checkNumQueens()){
            c11.setText("Q");
            vetor[2][2] = "Q";
        }
    }//GEN-LAST:event_c11ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed
        // casa 12 
        if (num.checkNumQueens()){
            c12.setText("Q");
            vetor[3][2] = "Q";
        }
    }//GEN-LAST:event_c12ActionPerformed

    private void c13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c13ActionPerformed
        // casa 13 
        if (num.checkNumQueens()){
            c13.setText("Q");
            vetor[0][3] = "Q";
        }
    }//GEN-LAST:event_c13ActionPerformed

    private void c14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c14ActionPerformed
        // casa 14
        if (num.checkNumQueens()){
            c14.setText("Q");
            vetor[1][3] = "Q";
        }
    }//GEN-LAST:event_c14ActionPerformed

    private void c15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c15ActionPerformed
        // casa 15 
        if (num.checkNumQueens()){
            c15.setText("Q");
            vetor[2][3] = "Q";
        }    
    }//GEN-LAST:event_c15ActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        
       num.resetNumQueens();
        // Reiniciar o tabuleiro
        c1.setText("");
        c2.setText("");
        c3.setText("");
        c4.setText("");
        c5.setText("");
        c6.setText("");
        c7.setText("");
        c8.setText("");
        c9.setText("");
        c10.setText("");
        c11.setText("");
        c12.setText("");
        c13.setText("");
        c14.setText("");
        c15.setText("");
        c16.setText("");
        // limpa os valores do vetor
        for(int l = 0; l < 4; l++){
            for(int c = 0; c < 4; c++){
                vetor[l][c] = "";
                }        
    }//GEN-LAST:event_reiniciarActionPerformed
        status.setText("");
        //habilita botões novamente
        c1.setEnabled(true);
        c2.setEnabled(true);
        c3.setEnabled(true);
        c4.setEnabled(true);
        c5.setEnabled(true);
        c6.setEnabled(true);
        c7.setEnabled(true);
        c8.setEnabled(true);
        c9.setEnabled(true);
        c10.setEnabled(true);
        c11.setEnabled(true);
        c12.setEnabled(true);
        c13.setEnabled(true);
        c14.setEnabled(true);
        c15.setEnabled(true);
        c16.setEnabled(true);  
        contador++;
        
    }
    private void checarRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarRespostaActionPerformed
        // checa se resposta está correta 
        
        boolean jogadorGanhou = VerificarVencedor();
        if(jogadorGanhou){
            status.setText("Você ganhou!");
        }else {
            status.setText("Você perdeu!");
        } 
    }//GEN-LAST:event_checarRespostaActionPerformed

    private void reiniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciar1ActionPerformed
        // botao desistir
        
        /**/
      
        FileWriter fl;
        
        try {
            fl = new FileWriter("log.txt");
            BufferedWriter bw = new BufferedWriter(fl);
            bw.write("O jogador conseguiu vencer o jogo.");
            bw.close();
        } catch (IOException ex) {
           System.out.println(ex.getClass());
        }
        
        /**/
        
        // primeiro reiniciar o tabuleiro
        c1.setText("");
        c2.setText("");
        c3.setText("");
        c4.setText("");
        c5.setText("");
        c6.setText("");
        c7.setText("");
        c8.setText("");
        c9.setText("");
        c10.setText("");
        c11.setText("");
        c12.setText("");
        c13.setText("");
        c14.setText("");
        c15.setText("");
        c16.setText("");
        // desabilitar botões e mostrar respostas
        status.setText("Você perdeu!");
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        c6.setEnabled(false);
        c7.setEnabled(false);
        c8.setEnabled(false);
        c9.setEnabled(false);
        c10.setEnabled(false);
        c11.setEnabled(false);
        c12.setEnabled(false);
        c13.setEnabled(false);
        c14.setEnabled(false);
        c15.setEnabled(false);
        c16.setEnabled(false);   
        // mostra
        c3.setText("Q");
        c5.setText("Q");
        c12.setText("Q");
        c14.setText("Q");   
    }//GEN-LAST:event_reiniciar1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         /*FileWriter fl;
        
        try {
            fl = new FileWriter("log.txt");
            BufferedWriter bw = new BufferedWriter(fl);
            bw.write("O jogador conseguiu vencer o jogo.");
            bw.close();
        } catch (IOException ex) {
           System.out.println(ex.getClass());
        }
        */
        FileWriter fw;
        
        try {fw = new FileWriter("log.txt");
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write("O jogador teve " + contador + "tentativas antes de finalizar o jogo.");
         
        if (VerificarVencedor() == true) {
            bw.write("O jogacor conseguiu vencer o jogo das 4 rainhas!");
        } else {
            bw.write("\nO jogador perdeu.");
        } 
         bw.close();
        
        
        } catch (IOException ex) {
           System.out.println(ex.getClass());
        }
    }//GEN-LAST:event_formWindowClosing
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // Reiniciar o tabuleiro
        c1.setText("");
        c2.setText("");
        c3.setText("");
        c4.setText("");
        c5.setText("");
        c6.setText("");
        c7.setText("");
        c8.setText("");
        c9.setText("");
        c10.setText("");
        c11.setText("");
        c12.setText("");
        c13.setText("");
        c14.setText("");
        c15.setText("");
        c16.setText("");
        // limpa os valores do vetor
        for(int l = 0; l < 4; l++){
            for(int c = 0; c < 4; c++){
                vetor[l][c] = "";
            }
    }                                       
   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c1;
    private javax.swing.JButton c10;
    private javax.swing.JButton c11;
    private javax.swing.JButton c12;
    private javax.swing.JButton c13;
    private javax.swing.JButton c14;
    private javax.swing.JButton c15;
    private javax.swing.JButton c16;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JButton checarResposta;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reiniciar;
    private javax.swing.JButton reiniciar1;
    private javax.swing.JTextField status;
    private javax.swing.JTextArea txtRegras;
    // End of variables declaration//GEN-END:variables
public int contador = 1;

  public boolean VerificarVencedor() {
         if(vetor[0][2] == "Q" & vetor [1][0] == "Q" & vetor [2][3] == "Q" & vetor [3][1] == "Q"){
            return true;
         } else {
             if(vetor[0][1] == "Q" & vetor [1][3] == "Q" & vetor[2][0] == "Q" & vetor[3][2] == "Q") {
                 return true;
             } else {
                 return false;
             }
         }
     }
  
  
  
  
  
  

}
